### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by chrisguindon** [eclipse/.github#3]
I was expecting to see a link to the CODE_OF_CONDUCT.md file in the root of the https://github.com/eclipse/sw360 repository.

I also tried to fork this repo in the jakarta.ee organization but I don't see any of these files.

**Comment by chrisguindon** [comment]
@caniszczyk do you know what I am missing here?

**Comment by caniszczyk** [comment]
The file won't be in the repo but the CONTRIBUTING.md and CODE_OF_CONDUCT.md will be reflected in all aspects of the GitHub UI: https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/

"While the file itself won’t appear in the file browser or Git history for each repository, it will be surfaced throughout developers’ workflows, such as when opening a new issue or when viewing the Community Profile, just as if it were committed to the repository directly."

If you send a PR, you should see the call out to the CoC and CONTRIBUTING.md

You could potentially make the .github repo a "template" repo and the files would just be copied over: https://help.github.com/en/articles/creating-a-template-repository

**Comment by chrisguindon** [comment]
Thanks @caniszczyk!

For some reason, I expected to see the files in the file browser!
