### ISSUE TITLE
Suggestion for the Enforcement section 

### ISSUE THREAD

**Issue by chrisguindon** [eclipse/.github#7]
```
Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at codeofconduct@eclipse.org. All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. The project team is obligated to maintain confidentiality with regard to the reporter of an incident. Further details of specific enforcement policies may be posted separately.

Project maintainers who do not follow or enforce the Code of Conduct in good faith may face temporary or permanent repercussions as determined by other members of the project's leadership.
```

This does not resonate with me. 

I don’t think it’s entirely correct to say that you are reporting an issue to the project team by sending an email to codeofconduct@eclipse.org.

I am thinking we should say something within the lines of:

"behavior may be reported by contacting the Eclipse Foundation Code of Conduct committee at codeofconduct@eclipse.org."

**Comment by borisbaldassari** [comment]
+1 Agreeing with Christopher. 

Furthermore, people facing an issue within a project may not wish to interact with the project's people for that matter.
In some other contexts (Apache for what I know/remember), there is a dedicated person IN the project to report such issues, AND there is someone at the foundation level in case it's not enough.
